# Data loader
data_loader:
  batch_size: 2048

# seed
setting:
  seed: 42

defaults:
  - optimizer: SGD
  - model: resnet18
  - MlFlow: server
  - hydra/job_logging: colorlog #to init plugin
  - hydra/hydra_logging: colorlog

# Trainer
trainer:
  num_epochs: 10
  patience: 30

# Infra configs
poutyne:
  logging: True
  root_logging_directory: "logging"
device: "cuda:0"

